apiVersion: v2
name: my-app
version: 1.1.0
dependencies:
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 22.0.7
    repository: https://charts.bitnami.com/bitnami
