apiVersion: v2
name: my-app
version: 0.1.0
dependencies:
  - name: postgresql
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.8.3
    repository: https://charts.bitnami.com/bitnami
