name: Module Versioning
concurrency:  #avoid concurrent runs on label events, might cause issues on super fast commits  ¯\_(ツ)_/¯
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, unlabeled]
  pull_request_target:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

env:
  DEFAULT_MODULE_VERSION: "0.1.0"
  HELM_VERSION: 3.10.0

jobs:
  detect:
    runs-on: ubuntu-22.04
    name: 'Check labels'
    outputs:
      release-type: ${{ steps.release.outputs.type }}
      is-merge-event: >-
        ${{ github.event_name == 'pull_request_target'
         && github.event.action == 'closed'
         && github.event.pull_request.merged == true }}
    steps:
      - name: Get all labels in PR
        id: pr-labels
        uses: joerick/pr-labels-action@0543b277721e852d821c6738d449f2f4dea03d5f # v1.0.9

      - name: Set Release type
        id: release
        run: |
          if [ -n "$GITHUB_PR_LABEL_MAJOR" ]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [ -n "$GITHUB_PR_LABEL_MINOR" ]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif [ -n "$GITHUB_PR_LABEL_PATCH" ]; then
            echo "type=patch" >> $GITHUB_OUTPUT
          elif [ -n "$GITHUB_PR_LABEL_NO_RELEASE" ]; then
            echo "type=no-release" >> $GITHUB_OUTPUT
          else
            echo "::error ::No release type labels found(patch/minor/major/no-release))"
            exit 2
          fi

  setup:
    name: 'set up helm'
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814  # v4.2.0
        with:
          version: ${{ env.HELM_VERSION }}

  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.changed-directories.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
      - name: Get list of changed directories
        id: changed-directories
        run: |
          list_changed_directories=$(git diff --diff-filter=d --name-only HEAD^ HEAD ':(exclude)*README.md' | xargs -L1 dirname | uniq | grep -Ev "^\." | sed -e 's/\/templates//;s/\/user-data//;s/\/policies//' | uniq || [[ $? == 1 ]] )
          echo $list_changed_directories

          declare -a matrix
          for changed_directory in $list_changed_directories;
          do
            module_name=$(echo $changed_directory | sed -e "s/\//_/g")
            matrix+="{\"module_name\": \"$module_name\", \"module_path\": \"$changed_directory\"},"
          done
          echo "matrix={\"include\":[$matrix]}" >> $GITHUB_OUTPUT
          echo $matrix

  decide-tags:
    needs:
      - generate-matrix
      - detect
    name: Decide Tags
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    if: needs.detect.outputs.release-type != 'no-release'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - name: 'Get Previous version'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@04e8485ecb6487243907e330d522ff60f02283ce" # v1.4.0
        with:
          fallback: ${{ env.DEFAULT_MODULE_VERSION }}
          prefix: ${{ matrix.module_name }}

      - name: 'Remove prefix from tag'
        id: previoustag-withoutprefix
        run: |
          # Removing moduleName from the complete tag i.e acm-v1.2.3 => v1.2.3
          withoutTag=$(echo ${{ steps.previoustag.outputs.tag }} | sed -e "s/^${{ matrix.module_name }}-//")
          
          # Storing variable in Step Output
          echo "tag=$withoutTag" >> $GITHUB_OUTPUT

      - name: 'Generate next version'
        id: next-semver
        uses: "WyriHaximus/github-action-next-semvers@18aa9ed4152808ab99b88d71f5481e41f8d89930" # v1.2.1
        with:
          version: ${{ steps.previoustag-withoutprefix.outputs.tag }}

      - uses: "cloudposse/github-action-matrix-outputs-write@ed06cf3a6bf23b8dce36d1cf0d63123885bb8375" # v1.0.0
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.module_name }}
          outputs: |-
              previous_tag: ${{ steps.previoustag-withoutprefix.outputs.tag }}
              new_tag: ${{ steps.next-semver.outputs[format('v_{0}', needs.detect.outputs.release-type )] }}

  comment:
    needs:
      - decide-tags
      - generate-matrix
    runs-on: ubuntu-22.04
    name: 'Comment on PR'
    if: needs.detect.outputs.is-merge-event == 'false'
    steps:
      - uses: "cloudposse/github-action-matrix-outputs-read@33cac12fa9282a7230a418d859b93fdbc4f27b5a" # v1.0.0
        id: read
        with:
          matrix-step-name: decide-tags

      - name: 'Prepare PR comments'
        id: comment_on_pr
        run: |
          list_of_modules=$(echo '${{ steps.read.outputs.result }}' | jq '.new_tag | keys[]' )
          previous_tags=$(echo '${{ steps.read.outputs.result }}' | jq '.previous_tag' )
          new_tags=$(echo '${{ steps.read.outputs.result }}' | jq '.new_tag')
          
          echo "# Release plan" >> prepare_comment.txt
          echo "| Module | Previous version | New version |" >> prepare_comment.txt
          echo "|--|--|--|" >> prepare_comment.txt
          
          declare -a array
          for module in $list_of_modules;
          do
            echo "| $module | $(echo $previous_tags | jq -r '.'$module) | $(echo $new_tags | jq -r '.'$module) |" >> prepare_comment.txt
          done          

      - name: Comment PR
        uses: "thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b" # v3.0.0
        with:
          file-path: prepare_comment.txt

  create-tag:
    
    needs:
      - generate-matrix
      - decide-tags
    name: Tag
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    if: ${{ (fromJson(needs.generate-matrix.outputs.matrix).include[0]) && (needs.detect.outputs.is-merge-event == 'true') }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - uses: "cloudposse/github-action-matrix-outputs-read@33cac12fa9282a7230a418d859b93fdbc4f27b5a" # v1.0.0
        id: read
        with:
          matrix-step-name: decide-tags

      - name: Fetch current SHA
        id: moduleSha
        run: |
          pwd
          module_sha=$(git log -1 --format="%H" -- ${{ matrix.module}})
          echo "sha=$module_sha" >> $GITHUB_OUTPUT

      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Github Actions Bot User
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Crete New Tag for Module
          git tag -a "${{ matrix.module_name }}-${{ fromJson(steps.read.outputs.result).new_tag[format('{0}', matrix.module_name )] }}" -m "Version ${{ fromJson(steps.read.outputs.result).new_tag[format('{0}', matrix.module_name )] }}" "${{ steps.moduleSha.outputs.sha }}"
          
          # Push Tag 
          git push origin ${{ matrix.module_name }}-${{ fromJson(steps.read.outputs.result).new_tag[format('{0}', matrix.module_name )] }}
  
  publish-helm:
    needs:
      - generate-matrix
      - decide-tags
      - create-tag
    name: Publish Helm Charts
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    if: needs.detect.outputs.release-type != 'no-release'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: decide-tags

      # Package chart
      - name: Package Helm chart
        working-directory: ${{ matrix.module_path }}
        run: |
          helm package . --destination ./packages

      # Merge index.yaml with new chart
      - name: Update Helm repo index.yaml
        run: |
          # Move packaged chart into helm dir
          mkdir -p helms
          cp ../artifacts/*.tgz helms/

          cd helms
          # Merge with existing index.yaml if it exists
          if [ -f ../packages/index.yaml ]; then
            helm repo index --merge ../packages/index.yaml .
          else
            helm repo index .
          fi

          # Move new tgz and index.yaml into packages dir
          mv *.tgz index.yaml ../packages/

          cd ..

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/
          git commit -m "Publish Helm chart ${{ matrix.module_name }} ${{ fromJson(steps.read.outputs.result).new_tag[format('{0}', matrix.module_name )] }}" || echo "No changes to commit"
          git push origin gh-pages

  create-release:
    needs:
      - generate-matrix
      - decide-tags
      - create-tag
    name: Release
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    if: needs.detect.outputs.release-type == 'major'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - uses: "cloudposse/github-action-matrix-outputs-read@33cac12fa9282a7230a418d859b93fdbc4f27b5a" # v1.0.0
        id: read
        with:
          matrix-step-name: decide-tags

      - name: Create Zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ matrix.module_path }}
        run: |
          zip -r ${{ matrix.module_name }}-${{ fromJson(steps.read.outputs.result).new_tag[format('{0}', matrix.module_name )] }}.zip . -x ".git/*" ".github/*"

      - name: Release new version
        uses: "softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8" #v2.0.9
        with:
          files: "${{ matrix.module_path }}/${{ matrix.module_name }}-${{ fromJson(steps.read.outputs.result).new_tag[format('{0}', matrix.module_name )] }}.zip"
          generate_release_notes: true
          tag_name: ${{ matrix.module_name }}-${{ fromJson(steps.read.outputs.result).new_tag[format('{0}', matrix.module_name )] }} # hack for now
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}